export interface TemplatePageGuide {
  bestFor: string;
  workflow: readonly [string, string, string];
  rationale: string;
  configuration: string;
  sample: string;
}

export const TEMPLATE_PAGE_GUIDES: Record<string, TemplatePageGuide> = {
  "/templates/action-tracker": {
    bestFor: "Teams and project owners who need one reliable list of commitments, owners, dates, and status.",
    workflow: ["Write each action as a specific outcome.", "Assign one owner and a realistic due date.", "Review the status column at the next meeting."],
    rationale: "The checkbox and action sit first because completion is the primary decision; ownership and timing follow in reading order.",
    configuration: "Use landscape orientation when actions or owner names are long. Add pages for each project or review period.",
    sample: "A one-page action register with owner, due-date, and status columns.",
  },
  "/templates/all-in-one-planner": {
    bestFor: "People who want one navigable planning file instead of separate yearly, monthly, weekly, habit, and notes PDFs.",
    workflow: ["Set the year and choose the sections you will actually use.", "Start from the contents page or section tabs.", "Review goals monthly and move weekly commitments into the planner pages."],
    rationale: "Repeated tabs and return links reduce page hunting on an e-ink tablet while preserving a familiar year-to-week planning hierarchy.",
    configuration: "Choose the start year, included sections, weekly layout, note pages, device, and handedness before generating the full planner.",
    sample: "A one-page planner overview showing the navigation and page hierarchy.",
  },
  "/templates/bill-tracker": {
    bestFor: "Households and freelancers who want a printable monthly record of bills and payment status.",
    workflow: ["List recurring and one-off bills before their due dates.", "Mark each row when payment clears.", "Use the notes field for confirmation numbers or exceptions."],
    rationale: "Paid status is visually separate from bill details so overdue items can be found with a quick scan.",
    configuration: "Landscape orientation gives payee and notes fields more room; portrait works for shorter monthly lists.",
    sample: "A one-page bill table with paid, due-date, amount, method, and notes fields.",
  },
  "/templates/birthday-tracker": {
    bestFor: "Families, teams, and community organizers keeping a reusable annual list of birthdays and important dates.",
    workflow: ["Add fixed annual dates month by month.", "Include the person or event and a short reminder.", "Review the next month before buying cards, gifts, or arranging events."],
    rationale: "A month-based overview stays reusable from year to year and makes crowded periods visible at a glance.",
    configuration: "Choose portrait for a compact annual reference or landscape for longer event notes.",
    sample: "A one-page annual event tracker organized by month.",
  },
  "/templates/book-notes": {
    bestFor: "Readers who want to retain a book’s central ideas, useful quotations, and actions after finishing it.",
    workflow: ["Record the book context before reading.", "Capture chapter notes and quotations while they are fresh.", "Finish with takeaways and one or two actions worth applying."],
    rationale: "Overview and chapter pages separate retrieval from reflection, so the file works both during reading and months later.",
    configuration: "Adjust line spacing for handwriting size and add enough pages for the length or density of the book.",
    sample: "A one-page book overview with takeaway, quotation, and action sections.",
  },
  "/templates/brain-dump": {
    bestFor: "Anyone who needs to clear a crowded mind before sorting ideas into tasks, decisions, and later items.",
    workflow: ["Write everything down without organizing it.", "Mark actionable items and move them into the lower categories.", "Discard, delegate, schedule, or store each remaining item."],
    rationale: "A large capture area comes before categories so organization does not interrupt recall.",
    configuration: "Choose wider line spacing for large handwriting and landscape orientation for broader category columns.",
    sample: "A one-page capture-and-sort worksheet.",
  },
  "/templates/bullet-journal": {
    bestFor: "Bullet-journal users who want reusable e-ink collections with built-in navigation instead of drawing every spread.",
    workflow: ["Choose the collections that match your planning routine.", "Use the index and future log to establish the system.", "Move between monthly, weekly, daily, and tracker pages with the PDF links."],
    rationale: "The kit keeps dot-grid flexibility while adding predictable navigation between commonly repeated collections.",
    configuration: "Set the device, binding side, title, date, and ink intensity before generating the complete linked journal.",
    sample: "A one-page bullet-journal collection showing the dot grid and navigation treatment.",
  },
  "/templates/calendar-2026": {
    bestFor: "E-ink users who want a complete dated year with correct weekday placement and month-to-month navigation.",
    workflow: ["Choose the calendar year and week-start convention.", "Use the contents page to jump to a month.", "Add appointments and deadlines directly to each dated grid."],
    rationale: "A contents page prevents long swiping, while one month per page preserves enough writing space for e-ink annotation.",
    configuration: "Select year, Monday or Sunday week start, device, orientation, and binding side.",
    sample: "A single dated month using the selected year and week-start convention.",
  },
  "/templates/cleaning-schedule": {
    bestFor: "Households dividing recurring cleaning work by room and day.",
    workflow: ["List the rooms or zones that need regular attention.", "Assign small tasks across the week.", "Check items off and revise tasks that are repeatedly skipped."],
    rationale: "Room grouping reduces context switching, while daily checkboxes make workload imbalance visible.",
    configuration: "Use landscape orientation for longer room or task labels and generate one page per week or household area.",
    sample: "A one-page weekly cleaning checklist grouped by room.",
  },
  "/templates/client-call": {
    bestFor: "Consultants, account managers, and freelancers preparing for and following up on client conversations.",
    workflow: ["Write the desired outcome and talking points before the call.", "Capture feedback and decisions during the conversation.", "Convert follow-ups into dated actions before closing the page."],
    rationale: "Preparation, live notes, and follow-up are kept on one page so context is not lost between stages.",
    configuration: "Adjust line spacing to your note density and page count to the number of scheduled calls.",
    sample: "A one-page client-call sheet with preparation, feedback, and follow-up areas.",
  },
  "/templates/cornell": {
    bestFor: "Students and professionals who revisit notes through cues, summaries, and active recall.",
    workflow: ["Take main notes in the large right column.", "Add questions or cue words in the left column after the session.", "Write the summary from memory before reviewing the notes."],
    rationale: "The asymmetric layout separates capture from retrieval practice, making review more active than rereading.",
    configuration: "Set cue-column width, summary visibility, line spacing, orientation, and page count for the subject.",
    sample: "A one-page Cornell sheet with cue, notes, and summary regions.",
  },
  "/templates/daily-focus": {
    bestFor: "People who need a realistic daily plan combining priorities, scheduled work, tasks, and notes.",
    workflow: ["Choose the three outcomes that define a successful day.", "Reserve time for focused work before filling small tasks.", "Close the day by moving unfinished work intentionally."],
    rationale: "Priorities appear before the schedule so urgent small tasks do not displace the day’s important work.",
    configuration: "Choose line density and page count to match handwriting and the number of days you want in one PDF.",
    sample: "A one-page daily plan with priorities, schedule, tasks, and notes.",
  },
  "/templates/daily-plan-adhd": {
    bestFor: "People who benefit from a low-choice daily plan with energy awareness and a deliberately small commitment list.",
    workflow: ["Check your available energy honestly.", "Choose one big outcome and no more than three must-do tasks.", "Put distracting ideas in the parking lot instead of changing plans."],
    rationale: "Hard limits reduce prioritization fatigue, and the parking lot preserves ideas without letting them interrupt the current plan.",
    configuration: "Use a comfortable line spacing and generate only the number of daily pages you are likely to use.",
    sample: "A one-page low-friction plan with energy, one big thing, must-dos, and parking lot.",
  },
  "/templates/daily-reflection": {
    bestFor: "People building a short daily reflection practice without committing to an open-ended journal page.",
    workflow: ["Set an intention at the beginning of the day.", "Record wins and lessons while they are specific.", "Name one improvement and use the open area for anything that needs more space."],
    rationale: "Prompted sections reduce blank-page friction while retaining a larger area for personal reflection.",
    configuration: "Adjust line spacing for handwriting size and generate a week or month of pages at a time.",
    sample: "A one-page guided reflection with intentions, wins, lessons, and journaling space.",
  },
  "/templates/debt-tracker": {
    bestFor: "People comparing debts and following either a balance-first snowball or interest-first avalanche payoff plan.",
    workflow: ["List every balance, rate, and minimum payment.", "Choose and mark the payoff order.", "Update balances and the progress indicator after each payment cycle."],
    rationale: "Account details and payoff progress share a page so strategy remains connected to current numbers.",
    configuration: "Use landscape for longer account names and create separate pages for different payoff phases if needed.",
    sample: "A one-page debt overview with payoff-order and progress fields.",
  },
  "/templates/decision-log": {
    bestFor: "Teams and individuals who need to remember why an important choice was made, not only what was decided.",
    workflow: ["State the decision and the problem it addresses.", "Record the options that were genuinely considered.", "Write the rationale, owner, and date while context is still available."],
    rationale: "Context and alternatives precede the outcome to preserve reasoning and reduce hindsight bias during later reviews.",
    configuration: "Choose line spacing based on expected detail and add pages according to the number of decisions under review.",
    sample: "A one-page log containing two structured decision records.",
  },
  "/templates/dot-grid": {
    bestFor: "Bullet journaling, diagrams, lettering, and flexible layouts that need alignment without prominent ruling.",
    workflow: ["Choose dot spacing for the scale of your handwriting or diagrams.", "Use dots as guides rather than fixed cells.", "Duplicate pages for collections that need a consistent grid."],
    rationale: "Low-contrast dots provide alignment while disappearing behind handwriting and sketches on e-ink screens.",
    configuration: "Set dot spacing, ink intensity, device, orientation, binding side, and page count.",
    sample: "A one-page dot grid at the selected spacing and page size.",
  },
  "/templates/eisenhower-matrix": {
    bestFor: "People sorting an overloaded task list by urgency and importance before scheduling work.",
    workflow: ["Place each task in one quadrant.", "Do or schedule important work first.", "Delegate urgent low-value work and remove tasks that are neither urgent nor important."],
    rationale: "The four equal quadrants force an explicit trade-off instead of allowing every task to appear equally important.",
    configuration: "Landscape gives each quadrant more horizontal writing room; page count can separate work, home, or project lists.",
    sample: "A one-page four-quadrant urgency and importance matrix.",
  },
  "/templates/expense-tracker": {
    bestFor: "Households and small businesses recording daily spending before reconciling a budget.",
    workflow: ["Log purchases while details are available.", "Assign a consistent category and payment method.", "Review totals against the budget at the end of the period."],
    rationale: "A compact ledger favors fast entry and later scanning over decorative summaries.",
    configuration: "Use landscape for longer descriptions and generate one or more pages per month.",
    sample: "A one-page expense ledger with category, amount, and payment method.",
  },
  "/templates/fitness-planner": {
    bestFor: "People planning a week of workouts before recording detailed performance elsewhere.",
    workflow: ["Assign each day a training focus.", "List exercises and target sets or repetitions.", "Review the week and adjust the next plan from what was completed."],
    rationale: "A weekly view exposes recovery and training balance that is hard to see in isolated session logs.",
    configuration: "Set exercise-row count, week structure, device orientation, and number of weeks where available.",
    sample: "A one-page weekly workout plan with exercise, sets, reps, and weight fields.",
  },
  "/templates/gratitude-journal": {
    bestFor: "People who want a brief morning and evening gratitude routine rather than an open-ended journal.",
    workflow: ["Write three specific things you appreciate in the morning.", "Notice useful moments during the day.", "Close with evening gratitude and a short reflection."],
    rationale: "Morning and evening prompts create a repeatable rhythm while limiting the effort required to maintain the habit.",
    configuration: "Choose line spacing and generate a manageable set of daily pages rather than an unnecessarily large file.",
    sample: "A one-page morning-and-evening gratitude journal.",
  },
  "/templates/grid": {
    bestFor: "Math, technical sketches, layouts, charts, and diagrams that need consistent square alignment.",
    workflow: ["Choose a grid size suited to the detail of the work.", "Use heavier structures along grid intersections.", "Create extra pages with the same spacing for multi-page problems or designs."],
    rationale: "A precise square grid makes proportions and alignment repeatable across handwriting and diagrams.",
    configuration: "Set grid spacing, ink intensity, orientation, binding side, device, and page count.",
    sample: "A one-page square grid at the selected physical spacing.",
  },
  "/templates/grocery-list": {
    bestFor: "Shoppers who want to group items by store section and reduce backtracking through aisles.",
    workflow: ["Add items under the matching food or household category.", "Check pantry quantities before leaving.", "Mark items as they enter the cart."],
    rationale: "Category grouping follows the way most stores are navigated and makes duplicate items easier to notice.",
    configuration: "Portrait works for compact lists; landscape provides more room for quantities and specific product notes.",
    sample: "A one-page grocery list divided into nine practical categories.",
  },
  "/templates/habit-tracker": {
    bestFor: "People tracking a small set of repeatable behaviors across a calendar month.",
    workflow: ["Name only habits that can be marked objectively.", "Check the grid at the same time each day.", "Review patterns at month-end instead of treating a missed day as failure."],
    rationale: "All 31 days remain visible beside each habit, making consistency and interruptions immediately apparent.",
    configuration: "Set the number of habit rows, month structure, orientation, and page count to avoid an overcrowded grid.",
    sample: "A one-page monthly habit grid with daily checkboxes.",
  },
  "/templates/inbox-capture": {
    bestFor: "People using a GTD-style inbox or any quick-capture habit for tasks, ideas, and unresolved items.",
    workflow: ["Capture an item in a single line without organizing it.", "Process the page at a scheduled time.", "Move each item to a project, calendar, reference list, or trash."],
    rationale: "Uniform checkbox lines minimize capture friction and postpone categorization until a deliberate review.",
    configuration: "Choose line spacing for handwriting size and generate enough pages for the interval between inbox reviews.",
    sample: "A one-page quick-capture inbox with checkbox lines.",
  },
  "/templates/kanban-board": {
    bestFor: "Individuals and small teams visualizing work as it moves through a limited set of workflow stages.",
    workflow: ["Name columns for the actual workflow.", "Write one deliverable per card slot.", "Move or rewrite cards during review and limit work in progress."],
    rationale: "Equal workflow columns make bottlenecks visible and keep attention on finishing work rather than starting more.",
    configuration: "Choose column count, labels, card density, and landscape orientation where available.",
    sample: "A one-page workflow board with task-card slots.",
  },
  "/templates/lecture-notes": {
    bestFor: "Students capturing key concepts, detailed notes, and questions during a class or recorded lecture.",
    workflow: ["Record the lecture context and key concepts first.", "Use the main area for chronological notes.", "List questions and unclear points for review after class."],
    rationale: "Concepts and questions are separated from the main notes so review can focus on understanding, not transcription alone.",
    configuration: "Adjust line spacing to writing speed and create one page per lecture or topic segment.",
    sample: "A one-page lecture sheet with concepts, notes, and questions.",
  },
  "/templates/lined": {
    bestFor: "General handwriting, journaling, meeting notes, and long-form writing that needs simple ruling.",
    workflow: ["Choose ruling that matches handwriting size.", "Enable a margin or header only when the writing method needs it.", "Generate a consistent stack of pages for the notebook or subject."],
    rationale: "The page stays deliberately neutral so ruling supports writing without imposing a workflow.",
    configuration: "Set ruling width, left margin, header zone, line density, device, orientation, and page count.",
    sample: "A one-page ruled sheet using the selected spacing and margins.",
  },
  "/templates/meal-planner": {
    bestFor: "Households planning breakfast, lunch, dinner, and snacks across a full week.",
    workflow: ["Add fixed commitments and leftover nights first.", "Plan meals around ingredients already available.", "Move missing ingredients into a grocery list."],
    rationale: "Meals are organized by both day and meal type, making gaps and repetitive choices visible before shopping.",
    configuration: "Landscape orientation provides the clearest seven-day grid; generate one page per planned week.",
    sample: "A one-page weekly meal grid covering four meal types.",
  },
  "/templates/meeting-notes": {
    bestFor: "Recurring team meetings, project reviews, and client conversations that must end with clear actions.",
    workflow: ["Write the objective and agenda before the meeting.", "Capture decisions and discussion notes under the relevant topic.", "Assign each action item before the meeting ends."],
    rationale: "Context and agenda come before a large notes area, with action items isolated at the bottom so commitments are not buried.",
    configuration: "Use line spacing that matches note density and generate one page per meeting or agenda block.",
    sample: "A one-page meeting record with context, agenda, notes, and action items.",
  },
  "/templates/monthly-budget": {
    bestFor: "Households comparing planned and actual spending across a stable set of monthly categories.",
    workflow: ["Set category budgets before the month begins.", "Update actual spending from the expense log.", "Review differences and record one adjustment for next month."],
    rationale: "Budget and actual values sit side by side so variance is visible without a separate calculation page.",
    configuration: "Landscape orientation improves category notes; line density affects the supporting notes area.",
    sample: "A one-page monthly budget with planned, actual, and notes fields.",
  },
  "/templates/monthly-calendar": {
    bestFor: "People who need a dated month overview with enough room for appointments, deadlines, and short notes.",
    workflow: ["Choose the starting month and number of months.", "Add fixed dates and deadlines first.", "Use the overview to balance commitments before planning individual weeks."],
    rationale: "A true calendar grid preserves weekday context while large cells leave space for handwriting on e-ink devices.",
    configuration: "Set starting month, month count, week start, device, orientation, and binding side.",
    sample: "A single correctly dated month using the selected calendar settings.",
  },
  "/templates/mood-tracker": {
    bestFor: "People observing broad mood patterns over a month without recording sensitive detail in a long journal.",
    workflow: ["Define what each mood level means to you.", "Mark one level consistently each day.", "Review clusters alongside brief notes about meaningful context."],
    rationale: "The month grid reveals patterns while the notes area prevents the scale from being mistaken for a complete explanation.",
    configuration: "Use portrait for a compact month view and adjust line spacing for the notes section.",
    sample: "A one-page 31-day mood grid with five levels and notes.",
  },
  "/templates/net-worth": {
    bestFor: "People taking a periodic snapshot of assets, liabilities, and net worth over time.",
    workflow: ["List current asset values and outstanding liabilities.", "Calculate the difference using the summary equation.", "Plot the same figure each month to observe direction rather than daily noise."],
    rationale: "The balance-sheet view explains the total, while the annual plot adds trend context without pretending to be financial advice.",
    configuration: "Landscape allows longer account labels; generate separate pages for households, businesses, or review periods.",
    sample: "A one-page assets-and-liabilities snapshot with a yearly trend grid.",
  },
  "/templates/one-on-one": {
    bestFor: "Managers and direct reports who want balanced recurring conversations rather than status-only meetings.",
    workflow: ["Prepare updates and discussion topics independently.", "Use the two-column area to capture both perspectives.", "Finish with decisions, support needed, and owned actions."],
    rationale: "Parallel columns give each participant visible space and keep shared action items distinct from discussion.",
    configuration: "Choose line spacing for conversation density and generate one page per scheduled one-to-one.",
    sample: "A one-page one-to-one agenda with updates, topics, and actions.",
  },
  "/templates/paper-summary": {
    bestFor: "Students and researchers extracting a paper’s claim, evidence, method, limitations, and relevance.",
    workflow: ["Record citation details and the research question.", "Summarize method and findings in your own words.", "Write limitations, connections, and what the paper changes for your work."],
    rationale: "Evidence and interpretation are separated so a later reader can distinguish what the paper reports from personal takeaways.",
    configuration: "Adjust line spacing and page count to the density of the paper and your review method.",
    sample: "A one-page academic-paper analysis sheet.",
  },
  "/templates/password-log": {
    bestFor: "People maintaining an offline reference for non-sensitive account hints or a securely stored paper password record.",
    workflow: ["Decide whether full passwords are appropriate for your storage situation.", "Record service, username, and a safe hint or reference.", "Store the exported file and printed pages securely."],
    rationale: "The layout favors concise lookup, but the page intentionally leaves security choices to the owner’s threat model.",
    configuration: "Set row count and orientation for account-name length; avoid unnecessary copies of sensitive information.",
    sample: "A one-page account log with service, username, and notes columns.",
  },
  "/templates/planner": {
    bestFor: "People who plan by week and want either open daily columns or an hourly schedule from morning to evening.",
    workflow: ["Choose a start date and the number of weeks.", "Block fixed commitments before adding flexible work.", "Use the overview links to move between weeks and review unfinished items."],
    rationale: "Seven equal columns preserve the shape of the week, while optional time slots support scheduling without forcing it on list-based planners.",
    configuration: "Set start date, week count, week-start convention, hourly slots, device, orientation, and handedness.",
    sample: "A single dated weekly page using the selected open or hourly layout.",
  },
  "/templates/project-brief": {
    bestFor: "Project leads aligning stakeholders on purpose, scope, ownership, risk, and success before execution starts.",
    workflow: ["State the objective and success criteria in measurable terms.", "Define what is inside and outside scope.", "Confirm stakeholders, risks, and immediate next steps together."],
    rationale: "The page keeps foundational decisions visible in one place, reducing the chance that scope and success are interpreted differently.",
    configuration: "Use landscape for longer scope statements and line spacing suited to the level of detail.",
    sample: "A one-page project brief with objective, scope, stakeholders, risks, and success criteria.",
  },
  "/templates/project-planner": {
    bestFor: "Project owners who want one linked PDF covering definition, milestones, tasks, risks, and working notes.",
    workflow: ["Define the project and success criteria first.", "Break the work into milestones, tasks, and owned risks.", "Use the contents page and return links during regular project reviews."],
    rationale: "Linked sections keep planning artifacts together while still allowing fast movement on a slower-refresh e-ink display.",
    configuration: "Choose the sections, row counts, notes pages, device, orientation, and binding side before generating the complete planner.",
    sample: "A one-page project overview showing the planner’s information hierarchy.",
  },
  "/templates/project-timeline": {
    bestFor: "Projects that need a simple visual sequence of milestones rather than a detailed Gantt chart.",
    workflow: ["Identify the few milestones that change project state.", "Add realistic dates and a concise completion description.", "Review dependencies and update the sequence when dates move."],
    rationale: "A linear path emphasizes order and major transitions without implying precision the plan does not have.",
    configuration: "Set milestone count and orientation for label length, then create separate pages for phases if needed.",
    sample: "A one-page milestone timeline with date and description fields.",
  },
  "/templates/quarterly-goals": {
    bestFor: "Individuals and teams translating a small number of quarterly outcomes into monthly work and measurable indicators.",
    workflow: ["Choose no more goals than the quarter can support.", "Define evidence of progress for each goal.", "Break the work into monthly checkpoints and review indicators regularly."],
    rationale: "Goals, monthly actions, and indicators share the same view so activity remains connected to the intended outcome.",
    configuration: "Set quarter, year, goal density, device, orientation, and page count where appropriate.",
    sample: "A one-page quarter overview with goals, monthly breakdowns, and indicators.",
  },
  "/templates/reading-log": {
    bestFor: "Readers, students, and book groups maintaining a concise record of completed or assigned books.",
    workflow: ["Add the title and author when reading begins.", "Record start and finish dates consistently.", "Add a rating and one useful note after completion."],
    rationale: "A ledger format supports many books on one page and makes reading pace and preferences easy to review.",
    configuration: "Landscape gives title and notes columns more room; add pages based on expected reading volume.",
    sample: "A one-page reading ledger with dates, rating, and notes.",
  },
  "/templates/recipe-page": {
    bestFor: "Home cooks building a consistent personal recipe collection for kitchen use or e-ink reference.",
    workflow: ["Record yield, timing, and ingredients before instructions.", "Write steps in the exact order they are performed.", "Use notes for substitutions and changes after cooking."],
    rationale: "Ingredients and ordered steps remain visually distinct so the page is easy to scan with occupied hands.",
    configuration: "Adjust line spacing and orientation for recipe length; generate extra pages for long methods or variations.",
    sample: "A one-page recipe with ingredient checklist, numbered method, and notes.",
  },
  "/templates/revision-planner": {
    bestFor: "Students planning revision from subject confidence and available weeks rather than rereading everything equally.",
    workflow: ["Rate confidence by subject or topic.", "Give low-confidence, high-value topics the earliest sessions.", "Check sessions off and update confidence from practice results."],
    rationale: "Confidence and schedule are connected so revision time follows evidence of need instead of familiarity.",
    configuration: "Set subject count, schedule length, orientation, and page count for the exam period.",
    sample: "A one-page subject overview with confidence and revision schedule.",
  },
  "/templates/routine-tracker": {
    bestFor: "People tracking a weekly sequence of morning, evening, household, or care routines.",
    workflow: ["Break the routine into observable steps.", "Mark completion for each day without scoring perfection.", "Change steps that repeatedly fail at the same point."],
    rationale: "A seven-day grid reveals whether the routine itself is practical, not merely whether motivation was high.",
    configuration: "Set routine-row count, labels, week structure, and orientation based on the length of each step.",
    sample: "A one-page weekly routine grid with daily checkboxes.",
  },
  "/templates/savings-challenge": {
    bestFor: "People building a year-long saving habit through small weekly contributions and visible progress.",
    workflow: ["Choose a contribution pattern that fits actual cash flow.", "Mark each deposit when it is made.", "Track the running total and adjust future weeks rather than abandoning the challenge."],
    rationale: "Weekly actions and cumulative progress appear together, connecting a small habit to the final target.",
    configuration: "Set weekly amount pattern, target, starting point, and orientation where available.",
    sample: "A one-page 52-week saving checklist with running totals.",
  },
  "/templates/self-care-checklist": {
    bestFor: "People who benefit from a gentle daily reminder of basic routines, mood, energy, hydration, and notes.",
    workflow: ["Choose only care actions that are relevant today.", "Mark routines without treating the page as a performance score.", "Use mood, energy, and notes to notice what support is needed."],
    rationale: "Routine prompts and simple scales reduce recall effort while leaving space for context that a checkbox cannot capture.",
    configuration: "Use line spacing suited to notes and generate a short run of pages so the checklist can evolve.",
    sample: "A one-page self-care checklist with routines, mood, energy, hydration, and notes.",
  },
  "/templates/shutdown-checklist": {
    bestFor: "Knowledge workers who want a consistent boundary between the workday and personal time.",
    workflow: ["Process messages and unfinished tasks.", "Record tomorrow’s first focus and any waiting items.", "Complete the final shutdown steps and stop revisiting the day’s open loops."],
    rationale: "A repeatable sequence externalizes unfinished work and makes the next starting point explicit.",
    configuration: "Choose line spacing and page count for a week or month of workdays.",
    sample: "A one-page end-of-day checklist with tomorrow’s focus.",
  },
  "/templates/sinking-funds": {
    bestFor: "Households saving gradually for irregular but expected expenses such as repairs, travel, fees, or replacements.",
    workflow: ["Name each future expense and target amount.", "Set a sustainable recurring contribution.", "Update saved amounts and progress after each contribution."],
    rationale: "Each fund keeps target, contribution, and progress together so long-term expenses do not disappear inside a general savings total.",
    configuration: "Landscape works well for long fund names; create separate pages for personal, household, or business funds.",
    sample: "A one-page sinking-fund register with per-goal progress indicators.",
  },
  "/templates/sleep-log": {
    bestFor: "People recording sleep timing and perceived quality to discuss patterns or improve routines.",
    workflow: ["Record bedtime and wake time consistently.", "Add duration and a simple quality rating.", "Use notes for context such as travel, illness, caffeine, or interruptions."],
    rationale: "Timing, duration, rating, and context sit in one row so patterns can be reviewed without implying medical diagnosis.",
    configuration: "Choose orientation based on note length and generate one page per tracking period.",
    sample: "A one-page sleep ledger with timing, duration, quality, and notes.",
  },
  "/templates/three-priorities": {
    bestFor: "People who make better progress with three explicit outcomes instead of a long undifferentiated task list.",
    workflow: ["Choose three outcomes that matter today.", "Break each into only the next necessary actions.", "Record the daily win before deciding what carries forward."],
    rationale: "Large numbered areas make trade-offs visible and prevent low-value tasks from occupying the entire page.",
    configuration: "Portrait emphasizes the vertical sequence; landscape provides more room for subtasks.",
    sample: "A one-page focus sheet with three priorities, subtasks, and a daily win.",
  },
  "/templates/time-block": {
    bestFor: "People planning a day by allocating time explicitly rather than working from an unordered task list.",
    workflow: ["Block fixed commitments and breaks first.", "Assign focused work to realistic open periods.", "Compare the plan with what happened and adjust future estimates."],
    rationale: "Half-hour rows expose overcommitment and make transitions, travel, and recovery time harder to ignore.",
    configuration: "Set day range, time labels, interval density, orientation, and page count for your routine.",
    sample: "A one-page daily schedule with half-hour time blocks.",
  },
  "/templates/travel-planner": {
    bestFor: "Travelers who want destination details, packing, daily itinerary, budget, and notes in one portable page set.",
    workflow: ["Record dates, destination, and budget constraints.", "Build the packing list from activities and conditions.", "Plan morning, afternoon, and evening anchors while leaving room for changes."],
    rationale: "Preparation and itinerary live together so packing decisions remain connected to the actual trip plan.",
    configuration: "Use landscape for longer itinerary notes and generate one page per destination or travel day.",
    sample: "A one-page trip plan with packing checklist, itinerary, budget, and notes.",
  },
  "/templates/vision-board": {
    bestFor: "People turning broad aspirations into a balanced written overview across several areas of life.",
    workflow: ["Choose the life areas that currently matter.", "Write specific desired states rather than slogans.", "Add one observable next step for each active area."],
    rationale: "Separate life-area regions encourage balance while keeping the page grounded in written goals that work on monochrome e-ink.",
    configuration: "Landscape offers wider goal areas; use a custom title and date to define the board’s review period.",
    sample: "A one-page structured vision board divided by life area.",
  },
  "/templates/weekly-dated": {
    bestFor: "People who want a ready-dated week in either horizontal day columns or vertical day rows.",
    workflow: ["Choose a start date and layout direction.", "Add fixed commitments and weekly outcomes.", "Use the generated sequence as a short planning run rather than an undated archive."],
    rationale: "Real dates remove setup work, while two layout directions support different handwriting and planning styles.",
    configuration: "Set start date, week count, vertical or horizontal layout, week start, and device settings.",
    sample: "A single dated week in the selected row or column layout.",
  },
  "/templates/weekly-review": {
    bestFor: "People closing a week deliberately before planning the next one.",
    workflow: ["List wins and completed work from evidence.", "Capture lessons and unfinished commitments.", "Choose the next week’s focus and move tasks intentionally."],
    rationale: "Reflection comes before forward planning so the next week is informed by what actually happened.",
    configuration: "Adjust line spacing for reflection depth and generate one page for each weekly review period.",
    sample: "A one-page weekly review with wins, lessons, carry-forward tasks, and next focus.",
  },
  "/templates/weight-loss-tracker": {
    bestFor: "People recording a 12-week weight trend alongside weekly changes and contextual notes.",
    workflow: ["Record measurements under consistent conditions.", "Calculate weekly change without overreacting to one value.", "Use the graph and notes to review the overall direction."],
    rationale: "A blank trend chart puts individual measurements in context while avoiding decorative or invented analytics.",
    configuration: "Landscape provides a wider chart; create separate pages for successive 12-week periods.",
    sample: "A one-page 12-week log with change fields and a blank progress chart.",
  },
  "/templates/workout-log": {
    bestFor: "People recording one gym or training session per page with enough detail to compare future sessions.",
    workflow: ["Record session context and warm-up.", "Log sets, repetitions, and weight as performed.", "Finish with cardio, notes, and one adjustment for the next session."],
    rationale: "One session per page leaves room for actual performance data and keeps it separate from weekly planning.",
    configuration: "Set exercise-row count, warm-up or cardio sections, orientation, and page count where available.",
    sample: "A one-page workout log with session header, exercise grid, cardio, and notes.",
  },
  "/templates/semester-planner": {
    bestFor: "Students who want one linked semester file for courses, timetables, assignments, exams, and lecture notes.",
    workflow: ["Set the semester name and start month before generating.", "Use the index to jump to a course or tracking page.", "Review assignments and exams weekly, then keep lecture notes beside the plan."],
    rationale: "The linked academic sequence keeps planning, deadlines, and notes in one file without turning the semester into a revision schedule.",
    configuration: "Set the semester name, start month, week-start convention, device, orientation, and binding side.",
    sample: "The semester overview page with contents and academic goal areas.",
  },
  "/templates/literature-review-matrix": {
    bestFor: "Students and researchers comparing several sources against one research question or topic.",
    workflow: ["Name the topic and research question before reading deeply.", "Capture one source per row across method, findings, limitations, and themes.", "Use the synthesis area to compare patterns and disagreements across sources."],
    rationale: "A cross-source matrix exposes similarities and gaps that a single-paper summary cannot show.",
    configuration: "Set the topic, research question, page count, device, orientation, and binding side; use landscape when entries need more width.",
    sample: "One source-comparison page with six analysis columns and synthesis lines.",
  },
  "/templates/quarterly-review": {
    bestFor: "Individuals and teams who want to close a quarter using evidence from completed work before choosing the next priorities.",
    workflow: ["Record wins and the evidence behind them.", "Name lessons, unfinished work, and what should stop, start, or continue.", "Choose a small set of next-quarter priorities from that review."],
    rationale: "Retrospective prompts keep this page focused on what happened and what was learned, rather than duplicating a forward-looking quarterly goals plan.",
    configuration: "Choose the quarter, year, page count, device, orientation, binding side, and ink intensity.",
    sample: "A one-page quarter closeout with evidence, lessons, unfinished work, and next priorities.",
  },
  "/templates/monthly-reset": {
    bestFor: "People who want a short monthly reset that turns reflection into a practical plan and a few repeatable routines.",
    workflow: ["Review wins, friction, and lessons from the month.", "Set priorities, commitments, and key dates for the next month.", "Choose routines and first actions that make the plan easier to start."],
    rationale: "The three-page sequence moves from reflection to planning to action without adding a full monthly calendar or a long goal-setting system.",
    configuration: "Set the start month, device, orientation, binding side, and ink intensity; the pack always contains three pages.",
    sample: "The first reflection page with wins, friction, lessons, and carry-forward space.",
  },
  "/templates/yearly-roadmap": {
    bestFor: "Individuals and small teams connecting a year’s direction to quarterly outcomes and monthly checkpoints.",
    workflow: ["Write the few outcomes that would make the year meaningful.", "Assign them to realistic quarters.", "Use monthly pages to define checkpoints and review progress."],
    rationale: "The year, quarter, and month levels remain connected without forcing day-to-day detail into a strategic overview.",
    configuration: "Set year, page structure, orientation, and device; use landscape when quarterly notes are long.",
    sample: "A one-page yearly overview with quarterly goal regions.",
  },
};
